env_files:
  github_token: ~/.GH_TOKEN.txt

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: nonf
    targets:
      - darwin_amd64
      - windows_amd64
      - freebsd_amd64
      - openbsd_amd64
      - netbsd_amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
  - id: linux
    goos:
      - linux
    goarch:
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    flags:
      - -trimpath
    ldflags:
      - -s -w
  - id: nf
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

release:
  github:
    owner: semihalev
    name: sdns
  prerelease: false
  draft: true

archives:
  - 
    name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}_sha256sums.txt'
  algorithm: sha256

changelog:
  skip: true

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    builds:
      - nf
    homepage:  https://sdns.dev
    description: Fast DNS Resolver
    maintainer: Yasar Alev <semihalev@gmail.com>
    license: MIT
    bindir: /usr/bin
    empty_folders:
      - /var/lib/sdns
    files:
      "contrib/linux/sdns.service": "/lib/systemd/system/sdns.service"
    config_files:
      "contrib/linux/sdns.conf": "/etc/sdns.conf"
    scripts:
      postinstall: "contrib/linux/adduser.sh"
    release: 1
    formats:
    - deb
    - rpm
    overrides:
      deb:
        dependencies:
          - systemd-sysv
      rpm:
        replacements:
          amd64: x86_64
        dependencies:
          - systemd