env_files:
  github_token: ~/.GH_TOKEN.txt

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
- env:
    - CGO_ENABLED=0
  targets:
    - darwin_amd64
    - windows_amd64
    - freebsd_amd64
    - freebsd_arm
    - linux_amd64
    - linux_arm
    - openbsd_amd64
    - netbsd_amd64
  flags:
    - -trimpath
  ldflags:
    - -s -w

release:
  github:
    owner: semihalev
    name: sdns
  prerelease: false
  draft: true

archives:
  - 
    name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}_sha256sums.txt'
  algorithm: sha256

changelog:
  skip: true

nfpms:
  - file_name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    homepage:  https://sdns.dev
    description: Fast DNS Resolver
    maintainer: Yasar Alev <semihalev@gmail.com>
    license: MIT
    bindir: /usr/bin
    meta: true
    empty_folders:
      - /var/lib/sdns
    files:
      "contrib/linux/sdns.service": "/lib/systemd/system/sdns.service"      
    config_files:
      "contrib/linux/sdns.conf": "/etc/sdns.conf"
    scripts:
      postinstall: "contrib/linux/adduser.sh"  
    formats:
    - deb
    - rpm
    overrides:
      deb:
        dependencies:
          - systemctl
      rpm:
        replacements:
          amd64: x86_64
        dependencies:
          - systemd