env_files:
  github_token: ~/.GH_TOKEN.txt

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
- env:
    - CGO_ENABLED=0
  targets:
    - darwin_amd64
    - windows_amd64
    - freebsd_amd64
    - freebsd_arm
    - linux_amd64
    - linux_arm
    - openbsd_amd64
    - netbsd_amd64
  flags:
    - -trimpath
  ldflags:
    - -s -w

release:
  github:
    owner: semihalev
    name: sdns
  prerelease: false
  draft: true

archives:
  - 
    name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_sha256sums.txt'
  algorithm: sha256

changelog:
  skip: true
