name: "Tidier"

on:
  schedule:
    - cron: "30 9 * * 2" # Weekly build

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run go-mod-tidy
        uses: sue445/go-mod-tidy-pr@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_name: tidybot
          git_user_email: tidybot@github.com
          reviewer: semihalev
